def fill_db():
    Products.objects.create(title='Помидор', description='Помидор крассный', price=100 , category='Овощи')
    Products.objects.create(title='Огурец', description='Огурцец стандартный', price=190 , category='Овощи')
    Products.objects.create(title='Баклажан', description='Баклажан стандартный', price=10 , category='Овощи')
    Products.objects.create(title='Морковь', description='Морковь стандартная', price=11 , category='Овощи')
    Products.objects.create(title='Капуста', description='Капуста стандартная', price=16 , category='Овощи')
    Products.objects.create(title='Яблоко', description='Яблоко РедГолд', price=100 , category='Фрукты')
    Products.objects.create(title='Груша', description='Груша украинская', price=200 , category='Фрукты')
    Products.objects.create(title='Виноград', description='Виноград КишьМышь', price=250 , category='Фрукты')
    Products.objects.create(title='Слива', description='Слива большая', price=345 , category='Фрукты')
    Products.objects.create(title='Укроп', description='Укроп', price=20 , category='Зелень')
    Products.objects.create(title='Петрушка', description='Петрушка', price=100 , category='Зелень')
    Products.objects.create(title='Руккола', description='Руккола', price=100 , category='Зелень')
    Products.objects.create(title='Базилик', description='Базилик', price=100 , category='Зелень')
    Products.objects.create(title='Тимьян', description='Тимьян', price=100 , category='Зелень')
    Products.objects.create(title='Розмарин', description='Розмарин', price=100 , category='Зелень')
    Products.objects.create(title='Апельсин', description='Апельсин', price=100 , category='Цитрусы')
    Products.objects.create(title='Лимон', description='Лимон', price=100 , category='Цитрусы')
    Products.objects.create(title='Манго', description='Манго', price=100 , category='Цитрусы')
    Products.objects.create(title='Авокадо', description='Авокадо', price=100 , category='Цитрусы')
    Products.objects.create(title='Ананас', description='Ананас', price=100 , category='Цитрусы')
    Products.objects.create(title='Лайм', description='Лайм', price=100 , category='Цитрусы')
    Products.objects.create(title='Томат в соб. соку', description='Томат в собственном соку', price=100 , category='Консервация')
    Products.objects.create(title='Огурец сол.', description='Огурец соленый', price=100 , category='Консервация')
    Products.objects.create(title='Ананас консерв.', description='Ананас консервированный', price=100 , category='Консервация')
    Products.objects.create(title='Томат', description='Томат', price=100 , category='Консервация')
    Products.objects.create(title='Кетчуп', description='Кетчуп', price=100 , category='Консервация')
    Products.objects.create(title='Топинг малин.', description='Топинг малиновый', price=100 , category='Консервация')
    Products.objects.create(title='Соль', description='Соль 1кг', price=100 , category='Бакалея, крупы, яйцо')
    Products.objects.create(title='Сахар', description='Сахар 1кг', price=100 , category='Бакалея, крупы, яйцо')
    Products.objects.create(title='Мука', description='Мука 5кг', price=100 , category='Бакалея, крупы, яйцо')
    Products.objects.create(title='Рис басм.', description='Рис басмати', price=100 , category='Бакалея, крупы, яйцо')
    Products.objects.create(title='Крохмал кукур.', description='Крохмал кукурузный', price=100 , category='Бакалея, крупы, яйцо')
    Products.objects.create(title='Яйцо кур.', description='Яйцо куриное', price=100 , category='Бакалея, крупы, яйцо')
    Products.objects.create(title='Масло подс.', description='Масло подсолнечное', price=100 , category='Бакалея, крупы, яйцо')


if __name__ == '__main__':
    fill_db()